coop_tilleuls_sylius_click_n_collect_shop_locations:
    path: /click-n-collect/locations/{shippingMethodCode}
    controller: coop_tilleuls_click_n_collect.controller.locations
    methods: GET

coop_tilleuls_sylius_click_n_collect_shop_collection_times:
    path: /click-n-collect/collection-times/{shipmentId}/{locationCode}
    controller: coop_tilleuls_click_n_collect.controller.collection_times
    methods: GET
